### PR TITLE
A few quality-of-life additions

### PR DESCRIPTION
**Pull request by Skylark13**
- Added a command line argument for the file to save or restore, so you can save different window layouts for different situations (dual monitor, remote, etc).
- Added a build batch file.

I know this is probably just a little one-off program, but it was useful to me, so why not to others? :)

### CODE REVIEW

**Comment by svensvond** [comment]
nice additions, i did something similar before i walked over the pull requests .. maybe a fork would be useful.

**Comment by Neo202020** [comment]
Just using this very handy tool but how do you save different layouts? Doesn't Save just save the current layout and restore that - how do you save your "home" layout and your "office" layout? thanks

**Comment by pngan** [comment]
> Just using this very handy tool but how do you save different layouts? Doesn't Save just save the current layout and restore that - how do you save your "home" layout and your "office" layout? thanks


Nice to hear that this little utility is of interest to others. I'll have a look at the pr, which looks to address the ability to store multiple layouts.

**Comment by pngan** [comment]
Updated to accommodate optional multiple screen layouts in another PR

**Comment by Neo202020** [comment]
Awesome!!

**Pull request closed without merging**
